apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: contact-service
  name: contact-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: contact-service
    spec:
      containers:
      - image: dekapx/contact-service
        name: contact-service
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: contact-service
  name: contact-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: contact-service
  type: ClusterIP
status:
  loadBalancer: {}
