server:
    port: 9192
spring:
    application:
        name: audit-service
    datasource:
        platform: POSTGRESQL
        username: 'dekapx'
        password: 'passw0rd'
        url: jdbc:postgresql://localhost:5432/testdb
        jpa:
            hibernate:
                ddl-auto: update
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
            show-sql: true
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379

