server:
    port: 8081
spring:
    application:
        name: spring-boot-redis-cache
    datasource:
        password: passw0rd
        url: jdbc:postgresql://localhost:5432/testdb
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
