spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                max.poll.records: 50
                min.fetch.bytes: 5000
                fetch.max.wait.ms: 1000
        binder:
          brokers: localhost:9092

      bindings:
        producer-out-0:
          destination: test-topic-inbound
          producer:
            useNativeEncoding: true
        consumer-in-0:
          destination: test-topic-inbound
          consumer:
            batch-mode: true
            max-attempts: 1
            use-native-decoding: true