version: '3.8'
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=${USER_NAME}
      - POSTGRES_USER=${PASSWORD}
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

