version: '3.8'
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local