version: '3.8'
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=dekapx
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

#  docker container run --name docker-postgres -p 5432:5432
#  -e POSTGRES_USER=dekapx -e POSTGRES_PASSWORD=passw0rd -e
#  POSTGRES_DB=testdb -v pgdata:/var/lib/postgresql/data postgres:14.1