version: '3.8'
services:
  prometheus:
    image: 'bitnami/prometheus:2.43.0'
    ports:
      - '9090:9090'
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: 'grafana/grafana:9.5.1'
    ports:
      - '3000:3000'